version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deblauwebok-app
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    depends_on:
      - database
    networks:
      - deblauwebok-network
    environment:
      - APP_ENV=${APP_ENV:-local}
      - APP_DEBUG=${APP_DEBUG:-true}
      - APP_URL=${APP_URL:-http://localhost:8000}
      - DB_CONNECTION=${DB_CONNECTION:-mysql}
      - DB_HOST=database
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE:-laravel}
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-secret}

  database:
    image: mysql:8.0
    container_name: deblauwebok-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-laravel}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-secret}
      - MYSQL_USER=${DB_USERNAME:-laravel}
      - MYSQL_PASSWORD=${DB_PASSWORD:-secret}
    volumes:
      - deblauwebok-mysql-data:/var/lib/mysql
    networks:
      - deblauwebok-network

networks:
  deblauwebok-network:
    driver: bridge

volumes:
  deblauwebok-mysql-data:
    driver: local 